openapi: 3.1.1
info:
  version: "1.0"
  title: AppFirst
servers:
  - url: http://localhost:3000
paths:
  /hello:
    get:
      summary: hello world
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                type: object